steps:
  # Build mcp-server-mysql image (tag = git commit short SHA)
  - name: gcr.io/cloud-builders/docker
    id: Build mcp-server-mysql image
    args:
      - build
      - -t
      - europe-west3-docker.pkg.dev/$PROJECT_ID/ar-github-corax/mcp-server-mysql:$SHORT_SHA
      - -f
      - Dockerfile
      - .

  # Push mcp-server-mysql image
  - name: gcr.io/cloud-builders/docker
    id: Push mcp-server-mysql image
    args:
      - push
      - europe-west3-docker.pkg.dev/$PROJECT_ID/ar-github-corax/mcp-server-mysql:$SHORT_SHA

options:
  dynamic_substitutions: true
  pool:
    name: projects/production-283206/locations/europe-west3/workerPools/default
